version: "3.8"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    environment:
      - TZ=Europe/Stockholm
      - PLEX_CLAIM=exampletoken3217839821737931873
      - ADVERTISE_IP=<e.g https://plex.homepot.io:443
      - PLEX_UID=1002
      - PLEX_GID=1004
    volumes:
      - /mnt/Storage1/MediaLibrary/Plex/config:/config
      - /mnt/Storage1/MediaLibrary/Plex/transcode:/transcode
      - /mnt/Storage1/MediaLibrary/shared/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web, websecure"
      - "traefik.http.routers.plex.rule=Host(`plex.homepot.io`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=production"
networks:
  default:
    name: traefik-proxy
    external: true
